title: 0xtmax Hacking Hub
description: "CTF Writeups, Tryhackme, Hackthebox and Hacking Tools Cheatsheets"
author:
  name: "SomeHacker"
  email: "someone@somewebsite.somedomain"
  url: "https://0xtmax.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "0xtmax"
year : "2024"
